### ISSUE TITLE
v2.0 checklist

### ISSUE THREAD

**Issue by ankurk91** [ank91/ank-google-map#2]
Things to check before releasing v2.0
- [x] Refreshing page should return to same tab
- [x] Responsive settings page
- [x] Info Window text area when user have no rights to rich text - check responsive
- [x] Use extract to pass data to view 
- [x] Server side validation for lat & lng- may have to remove front-end validation
- [x] Upgrade paths
- [x] Multi lingual - generate pot file, add language domain
- [x] Dead Links
- [x] Revise FAQ on readme.txt
- [x] Generate min files
- [x] Update screenshots
